services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"

  api:
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      NMS_ENV: production
      NMS_ENFORCE_HTTPS: "true"
      NMS_ALLOW_NO_AUTH: "false"
      NMS_TERMINAL_ALLOW_INSECURE_ORIGIN: "false"
      NMS_TERMINAL_ALLOW_INSECURE_HOSTKEY: "false"
      NMS_SMTP_ALLOW_PLAINTEXT: "false"
      DB_SSLMODE: require

  worker:
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      NMS_ENV: production
      DB_SSLMODE: require

  postgres-exporter:
    environment:
      DB_SSLMODE_EXPORTER: require

  trap-receiver:
    environment:
      NMS_ENV: production
